### ISSUE TITLE
Adjust layout for homepage

### ISSUE THREAD

**Issue by ClemCB** [womenhackfornonprofits/together-in-the-uk#10]
Once we have the initial theme ready we need to adjust for the homepage design requested by TGIUK. 

MVP design below. Additional thoughts from team welcome:

![basic design idea for tgiuk](https://cloud.githubusercontent.com/assets/20284393/19907330/45f43b0e-a076-11e6-9eb6-d38039efe412.png)

**Comment by ghost** [comment]
Happy to work on this one

**Comment by lili2311** [comment]
Comments from Slack form the review of the initial commit of the homepage image menu

Can we change the Image Menu component to not be called *Gallery* but instead it is like a gallery but we need to customise it:

- [x] Rename Gallery -> Image Menu
- [x]  Check with TGIUK about the hover text on the image menu, if it is staying it needs more styling which can be done in a separate ticket.
- [x] each Image Menu Item links to a new page, so it needs to accept a Page form Wordpress the same way a Menu does currently.
- [x] Each Image Manu Item is a list item, with a link and a div which is a background image (it is a background image in this instance because it is not relevant content & it gives us more flexibility on how to style it and position it with CSS)
- [x] And the HTML will need amending to be semantic and to represent the fact that it a menu, please have a look at this example, the HTML structure should follow this. This makes the site accessible and easier for google to understand what is on the page:
http://codepen.io/lili2311/pen/wgaVzY

**Comment by VAO11** [comment]
Updated. Need to look into the hero slider as the theme utilises the post to populate the slider.
Do you want to create the slider from scratch or do you want to use a plug-in?

**Comment by lili2311** [comment]
Not a slider but a Hero just a static image with a slogan, this needs to be from scratch as the slider the theme has takes images from other posts instead of letting you upload one.

**Comment by VAO11** [comment]
The hero has been created created by @vao11.

**Comment by VAO11** [comment]
The css has been amended by @lili2311. Looking really good now
